### ISSUE TITLE
Error in __init__.py

### ISSUE THREAD

**Issue by TyBalduf** [ednusi/MatPy#3]
A user on the new matter modeling SE asked a [question](https://mattermodeling.stackexchange.com/questions/1478/how-to-find-youngs-modulus-using-stress-strain-curve-using-python) about using this package. They were able to successfully install in package, but importing the package resulted in an error in __init__.py:

```
from MatPy import material_analytics as ma
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/MatPy/__init__.py", line 2, in <module>
    from model import stress_strain
ModuleNotFoundError: No module named 'model'
```

Is this an additional dependency that is intended to be installed separately or was `model` intended to be included with Matpy?

**Comment by Embalzan** [comment]
Same error here. I was not able to use this package.  

Managed to find support on how to fix the problem [here](https://mattermodeling.stackexchange.com/questions/1478/how-to-find-youngs-modulus-using-stress-strain-curve-using-python).

Basically you need to follow Tyberius reply.

**Comment by TyBalduf** [comment]
> Same error here. I was not able to use this package.
> 
> Managed to find support on how to fix the problem [here](https://mattermodeling.stackexchange.com/questions/1478/how-to-find-youngs-modulus-using-stress-strain-curve-using-python).
> 
> Basically you need to follow Tyberius reply.

You should also check out the answers on that post, as there are a few other things that need fixing or at least a different interpretation.
